### ISSUE TITLE
Add build and update release scripts

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define-stream-kefir#9]
You can use the [Landscaper](https://www.npmjs.com/package/landscaper) cli to do this.

Code mod for adding build script: https://gist.githubusercontent.com/phillipskevin/75a3626b00dd32709b13132706cb7f30/raw/8bc798f05dcff27eb3fbe67a379575cf54d4c10e/add-build-script.js

Code mod for adding release scripts to package.json:
https://gist.githubusercontent.com/phillipskevin/75a3626b00dd32709b13132706cb7f30/raw/0ff49d113f38ca6ead5a8f2b0e8dcf1b65ac98f6/add-release-scripts.js

**Comment by frank-dspeed** [comment]
Only to complet the documentation can-migrate-codemod could be also used client side

**Comment by frank-dspeed** [comment]
@phillipskevin @matthewp  please close this i don't have access but it got just solved
